site_name: Advanced Liberty Tech Jam - Enterpise Deployments on VMs
nav:
  - Home: index.md
  - Workshop Labs: day1.md
  - Accessing lab environments: lab-env.md
theme: readthedocs  
extra_css: ["extra.css"]
